[theme]
primaryColor = "#1f77b4"      # Cool Blue
backgroundColor = "#f0f2f6"   # Light Grey
secondaryBackgroundColor = "#ffffff"  # White
textColor = "#333333"         # Dark Grey
font = "sans serif"           # Font type
